//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ManageController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManageController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ManageController", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метода за външно влизане бе премахнат..
        /// </summary>
        internal static string External_login_removed {
            get {
                return ResourceManager.GetString("External_login_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неуспешно потвърждаване на телефон..
        /// </summary>
        internal static string Failed_to_verify_phone {
            get {
                return ResourceManager.GetString("Failed_to_verify_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата бе сменена..
        /// </summary>
        internal static string Password_has_been_changed {
            get {
                return ResourceManager.GetString("Password_has_been_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата бе въведена..
        /// </summary>
        internal static string Password_has_been_set {
            get {
                return ResourceManager.GetString("Password_has_been_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефония номер бе добавен..
        /// </summary>
        internal static string Phone_number_added {
            get {
                return ResourceManager.GetString("Phone_number_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефония номер бе премахнат.
        ///.
        /// </summary>
        internal static string Phone_number_removed {
            get {
                return ResourceManager.GetString("Phone_number_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кодът ви е:.
        /// </summary>
        internal static string Security_code_sms {
            get {
                return ResourceManager.GetString("Security_code_sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системата за влизане в две стъпки бе активирана..
        /// </summary>
        internal static string Two_factor_authentication_set {
            get {
                return ResourceManager.GetString("Two_factor_authentication_set", resourceCulture);
            }
        }
    }
}
