//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AccountController", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля потвърдете имейла си като кликенте ето &lt;a href=&quot;{0}&quot;&gt;тук&lt;/a&gt;.
        /// </summary>
        internal static string Confirm_email_content {
            get {
                return ResourceManager.GetString("Confirm_email_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдете акаунта си.
        /// </summary>
        internal static string Confirm_your_account {
            get {
                return ResourceManager.GetString("Confirm_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден код..
        /// </summary>
        internal static string Invalid_code {
            get {
                return ResourceManager.GetString("Invalid_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неуспешно влизане..
        /// </summary>
        internal static string Invalid_login_attempt {
            get {
                return ResourceManager.GetString("Invalid_login_attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За да смените паролата си кликнете &lt;a href=&quot;{0}&quot;&gt;тук&lt;/a&gt;.
        /// </summary>
        internal static string Reset_password_email_content {
            get {
                return ResourceManager.GetString("Reset_password_email_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смяна на паролата.
        /// </summary>
        internal static string Reset_password_email_title {
            get {
                return ResourceManager.GetString("Reset_password_email_title", resourceCulture);
            }
        }
    }
}
