version: 0.1.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
       secure: h0CL0d02rQ0lXPrpXJ4XeJfgpcvHAbjyry+FK1x+atkOeSjUOCUJVKwIUBjPSK6s
before_build:
  - nuget restore ".\source\HappyMe.sln"
build:
  project: .\source\HappyMe.sln
  verbosity: minimal